### ISSUE TITLE
Add a pause button, so we can pause the timer

### ISSUE THREAD

**Issue by eyebo2** [BigBang1112/randomizer-tmf#6]
Sometimes we have to go AFK during a session. It would be nice to be able to pause the session and resume it.

**Comment by BigBang1112** [comment]
Pause is currently explained [here in the QnA](https://github.com/BigBang1112/randomizer-tmf/wiki/QnA#is-there-a-pause-button).

It cannot work currently (because the game is not controlled in real time), and is also controversial when it's integrated automatically into the current rule base.

If something would be made so that there's no time limit pressure, then that would be perhaps optional on/off time limit.

**Comment by eyebo2** [comment]
I just figured since RMC had a pause button, this one could too. But that makes sense about the game not being controlled in real time. I'll just add an extra half hour to the timer to mitigate the distractions that usually come up while I'm playing.

**Comment by BigBang1112** [comment]
For me personally, having a pause button is not what I would consider competitive when dealing with randomness. Having a short time to think about (and execute an author time on) a certain track is (imo) the only skillful aspect about the challenge. xd

If you're interested in "no time limit" then I could implement that instead.

**Comment by eyebo2** [comment]
I like a timelimit so that I don't end up playing hours and hours on end. :P But I'm not really playing this competitively. I just want to use it to discover some maps I haven't played before. :) Anyway, I think I'm okay with the way it is. Thanks for the replies.
